### ISSUE TITLE
Help: "the file did not appear to be a SAM or BAM format file"

### ISSUE THREAD

**Issue by Danrui-Wang** [metaGmetapop/metapop#18]
Hi @metaGmetapop , thank you for developing MetaPop!
At the very start, I encountered a problem, " the file did not appear to be a SAM or BAM format file".
Then I downloaded the test files, but the same error occurred again.
"MetaPop Started at: 18/10/2022 14:11:58
Checking: Kang_0011_ST001_A_only_virome_viruses for correctness... the file did not appear to be a SAM or BAM format file. Skipping this file."
I'm pretty sure the files are in BAM format. Maybe something else went wrong. Do you have any advice?

**Comment by marina-vn** [comment]
Hi @Danrui-Wang , I have run into the same problem, did you get any solution?

**Comment by yugen-miyahara** [comment]
Hi, I am getting the same problem and here is the error:

metapop --input_samples ~/for_metapop/bam --reference ~/for_metapop/reference --norm ~/for_metapop/Kang_test_dataset_bp_numbers.txt --preprocess_only
Using: 8 threads.
Combined genomes file already found.
Automatically predicted genes found. Skipping Prediction.
MetaPop Started at: 11/01/2023 19:36:07

Checking: Kang_0011_ST001_A_only_virome_viruses for correctness... the file did not appear to be a SAM or BAM format file. Skipping this file.
Checking: Kang_0011_ST003_A_only_virome_viruses for correctness... the file did not appear to be a SAM or BAM format file. Skipping this file.
Checking: Kang_0037_ST001_A_only_virome_viruses for correctness... the file did not appear to be a SAM or BAM format file. Skipping this file.
Traceback (most recent call last):
  File "/home/miyyu932/miniconda3/envs/metapop/bin/metapop", line 8, in <module>
    sys.exit(main())
  File "/home/miyyu932/miniconda3/envs/metapop/lib/python3.7/site-packages/metapop/metapop_main.py", line 297, in main
    metapop.metapop_filter.filt(original_bams, filter_command_base, bdb, threads, mag_contig_dict, mag_length_dict, joined_fastas)
  File "/home/miyyu932/miniconda3/envs/metapop/lib/python3.7/site-packages/metapop/metapop_filter.py", line 101, in filt
    pool = multiprocessing.Pool(min(threads, len(md_files)))
  File "/home/miyyu932/miniconda3/envs/metapop/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/miyyu932/miniconda3/envs/metapop/lib/python3.7/multiprocessing/pool.py", line 169, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

**Comment by marina-vn** [comment]
Did you made any progress with this?

**Comment by arisandz** [comment]
Hi!
I had the same issue. It resolved when i updated the samtools.
