### ISSUE TITLE
FileNotFoundError at the FST step 

### ISSUE THREAD

**Issue by MalickNdiye** [metaGmetapop/metapop#19]
Hi @metaGmetapop! The pipeline fails during the Fst calculation step. I get the following error message

> Error in eval(jsub, SDenv, parent.frame()) : object 'V1' not found
> Calls: [ -> [.data.table -> eval -> eval
> Execution halted
> Traceback (most recent call last):
>   File "/work/FAC/FBM/DMF/pengel/beemicrophage/mndiaye1/PHOSTER/workflow/.snakemake/conda/451345fbc2f73c6d7e98f3f6feffea2d_/bin/metapop", line 10, in <module>
>     sys.exit(main())
>   File "/work/FAC/FBM/DMF/pengel/beemicrophage/mndiaye1/PHOSTER/workflow/.snakemake/conda/451345fbc2f73c6d7e98f3f6feffea2d_/lib/python3.7/site-packages/metapop/metapop_main.py", line 351, in main
>     metapop.metapop_fst.perform_fst(microdiv_file, lengths_file, output_directory_base, threads)
>   File "/work/FAC/FBM/DMF/pengel/beemicrophage/mndiaye1/PHOSTER/workflow/.snakemake/conda/451345fbc2f73c6d7e98f3f6feffea2d_/lib/python3.7/site-packages/metapop/metapop_fst.py", line 267, in perform_fst
>     ct_lens = contig_lengths(lengths_file)
>   File "/work/FAC/FBM/DMF/pengel/beemicrophage/mndiaye1/PHOSTER/workflow/.snakemake/conda/451345fbc2f73c6d7e98f3f6feffea2d_/lib/python3.7/site-packages/metapop/metapop_fst.py", line 22, in contig_lengths
>     fh = open(file)
> FileNotFoundError: [Errno 2] No such file or directory: '../results/metapop/B_test/MetaPop/10.Microdiversity/global_contig_microdiversity.tsv'

Looks like the `global_contig_microdiversity.tsv` doesn't get created. Do you have any idea on what may be causing this issue. 

Thanks in advance!

**Comment by marina-vn** [comment]
Hi, I'm dealing with this same error, did you managed to solve it?

Best,

**Comment by MalickNdiye** [comment]
Unfortunately not, I decided to change tool

**Comment by marina-vn** [comment]
Which program did you change to? Any recommendations?

**Comment by MalickNdiye** [comment]
I switched to InStrain (https://instrain.readthedocs.io/en/latest/). Conceptually, it is very similar to Metapop. I highly recommend it.
