### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ShailNair** [metaGmetapop/metapop#21]
Hi,
Thanks for this great tool. I am trying to install this. However, the [readme file](https://github.com/metaGmetapop/metapop#readme) on the main repository and in [metapop-1.0](https://github.com/metaGmetapop/metapop/releases/tag/v1.0) shows different installation process and usage commands.

I tried both methods. When i install and try to run it as instructed on [metapop repository](https://github.com/metaGmetapop/metapop#readme) i get following error:

```
metapop --input_samples /home/metapop/0.1.bam/ \
--reference /home/metapop/merged.checkv_cleaned.viruses.fasta \
--norm /home/metapop/0.1.bam/reads.tsv \
--genes /home/metapop/0.2.orf_predict/merged.checkv_cleaned.viruses.fixed.fasta \
--output /home/metapop/0.3.output \
--snp_scale both \
--threads 30

Using: 30 threads.
Combined genomes file already found.
Using /home/metapop/0.2.orf_predict/merged.checkv_cleaned.viruses.fixed.fasta as the genes file.
Traceback (most recent call last):
  File "/home/miniconda3/envs/metapop/bin/metapop", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/metapop/lib/python3.7/site-packages/metapop/metapop_main.py", line 251, in main
    mag_contig_dict, mag_length_dict = metapop.metapop_helper_functions.create_mag_log(reference_fasta, output_directory_base+"/MetaPop/00.Log_and_Parameters/mags.txt", treat_as_mag)
  File "/home/miniconda3/envs/metapop/lib/python3.7/site-packages/metapop/metapop_helper_functions.py", line 114, in create_mag_log
    ref_files = dir_to_fastas(fasta_dir)
  File "/home/miniconda3/envs/metapop/lib/python3.7/site-packages/metapop/metapop_helper_functions.py", line 8, in dir_to_fastas
    for file in os.listdir(directory):
NotADirectoryError: [Errno 20] Not a directory: '/home/metapop//merged.checkv_cleaned.viruses.fasta'
```

If I use --reference as directory to reference file, I get following error

```
Using: 30 threads.
Combined genomes file already found.
Using /home/metapop/0.2.orf_predict/merged.checkv_cleaned.viruses.fixed.fasta as the genes file.
Traceback (most recent call last):
  File "/home/miniconda3/envs/metapop/bin/metapop", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/metapop/lib/python3.7/site-packages/metapop/metapop_main.py", line 251, in main
    mag_contig_dict, mag_length_dict = metapop.metapop_helper_functions.create_mag_log(reference_fasta, output_directory_base+"/MetaPop/00.Log_and_Parameters/mags.txt", treat_as_mag)
  File "/home/miniconda3/envs/metapop/lib/python3.7/site-packages/metapop/metapop_helper_functions.py", line 119, in create_mag_log
    mag_log, length_log, log_file = contig_log(ref_files)
  File "/home/miniconda3/envs/metapop/lib/python3.7/site-packages/metapop/metapop_helper_functions.py", line 25, in contig_log
    fh = open(file)
IsADirectoryError: [Errno 21] Is a directory: '/home/metapop/0.1.bam/ 
```

I also tried metapop v.1.0  by installing it through metapop conda package. 

```
Rscript MetaPop.R -dir /home/metapop/0.1.bam/ \
-assem /home/metapop/merged.checkv_cleaned.viruses.fasta \
-ct /home/metapop/0.1.bam/reads.tsv \
--genes /home/metapop/0.2.orf_predict/merged.checkv_cleaned.viruses.fixed.fasta \
--output /home/metapop/0.3.output \
--snp_scale both \
--threads 30
Fatal error: ??????'MetaPop.R': ?????????
```

Hope you can point me to the right way of installation and usage.

Thank you.

**Comment by ShailNair** [comment]
Solved by pulling the metapop-1.0 source code and creating a new Conda environment with all the dependencies.
